services:
  web:
    build: .
    restart: always
    container_name: cvproject
    entrypoint: ./entrypoint.sh
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    depends_on:
      - db
    networks:
      - cvproject_network

  db:
    image: postgres:17.0-alpine3.20
    restart: always
    container_name: cvproject-db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - cvproject_network

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - cvproject_network

  celery:
    build: .
    command: celery -A CVProject worker --loglevel=info
    env_file:
      - .env
    volumes:
      - .:/code
    depends_on:
      - web
      - rabbitmq
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
    networks:
      - cvproject_network


networks:
  cvproject_network:
    driver: bridge

volumes:
  postgres_data: {}
